<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>

    <TargetFramework>net9.0</TargetFramework>

    <ImplicitUsings>enable</ImplicitUsings>

    <Nullable>enable</Nullable>

    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>

    <PackageId>Brainy.Mapper</PackageId>

    <Version>1.0.1</Version>

    <Authors>Shakeel Iqbal</Authors>

    <Company>Brainy Solutions</Company>

    <Product>Brainy.Mapper</Product>

    <Description>

      It is a lightweight, high-performance object mapping library for .NET designed as a simple and efficient alternative to traditional object mappers.

    </Description>

    <PackageTags>

      mapper;automapper;mapping;dotnet
    </PackageTags>

    <RepositoryUrl>
      https://github.com/shakeel-iqbal-personal/Brainy.Mapper
    </RepositoryUrl>

    <RepositoryType>git</RepositoryType>

    <PackageLicenseExpression>MIT</PackageLicenseExpression>

    <PackageReadmeFile>README.md</PackageReadmeFile>

    <PackageIcon>brainy-mapper-icon.png</PackageIcon>

    <Title>Brainy Mapper</Title>

  </PropertyGroup>

  <ItemGroup>
    <None Include="docs\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="docs\brainy-mapper-icon.png" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.10" />
  </ItemGroup>

</Project>
